/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "micro-service"
include(":micro-service-gateway-server")
include(":micro-service-hello-client")
include(":micro-service-hello-server")
include(":micro-service-config-server")
include(":micro-service-common")
include(":micro-service-eureka-service")
