/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-server")
    implementation("org.springframework.cloud:spring-cloud-starter-bootstrap")
}

description = "micro-service-eureka-service"
