/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
}

dependencies {
    implementation("org.springframework.cloud:spring-cloud-config-server")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.cloud:spring-cloud-starter-bootstrap")
}

description = "micro-service-config-server"
