server:
  port: 7211

spring:
  application:
    name: hello-client
  cloud:
    config:
      uri: http://localhost:8888
    openfeign:
      oauth2:
        enabled: true
  profiles:
    active: dev

logging:
  root: debug
