server:
  port: 7111

spring:
  application:
    name: hello-server
  cloud:
    config:
      fail-fast: on
      uri: http://localhost:8888
  profiles:
    active: dev
logging:
  include-application-name: true
  pattern:
    correlation: "aaaa %X{tid:-NONE} "
