server:
  port: 8762

spring:
  application:
    name: eureka

eureka:
  security:
    username: admin
    password: admin
  instance:
    metadata-map:
      cluster: demo-cluster
    hostname: localhost
    prefer-ip-address: on
    lease-expiration-duration-in-seconds: 15
  client:
    registerWithEureka: false
    # 表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    fetchRegistry: false
    # 表示是否从eureka服务器获取注册信息，同上，这里不需要
    service-url:
      defaultZone: http://${eureka.security.username}:${eureka.security.password}@${eureka.instance.hostname}:${server.port}/eureka/ #是设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
    registry-fetch-interval-seconds: 5
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false


